const data = [
    {
      id: 1,
      title: ' Rosy',
      category: 'Pinned Chats',
      lastmsgtime: 60,
      img: '/contactimages/contact1.jpg',
      msg:'Good Day',
    },
    {
      id: 2,
      title: 'Jasmine',
      category: 'Group Chats',
      lastmsgtime: 30,
      img: '/contactimages/contact2.jpg',
      msg:'yeah I knew',
    },
    {
      id: 3,
      title: 'sarah',
      category: 'DMs',
      lastmsgtime: 100,
      img: '/contactimages/contact3.jpg',
      msg:'hell man',
    },
    {
      id: 4,
      title: 'Raj',
      category: 'Contacts',
      lastmsgtime: 3,
      img: '/contactimages/contact4.jpg',
      msg:'ok I got it',
    },
    {
      id: 5,
      title: 'Reva',
      category: 'Pinned Chats',
      lastmsgtime: 3,
      img: '/contactimages/contact5.jpg',
      msg:'enjoying ha',
    },
    {
      id: 6,
      title: 'smily',
      category: 'Group Chats',
      lastmsgtime: 10,
      img: '/contactimages/contact6.jpg',
      msg:'what is that',
    },
    {
      id: 7,
      title: 'lily',
      category: 'DMs',
      lastmsgtime: 140,
      img: '/contactimages/lily.ico',
      msg:'ntg',
    },
    ];
  export default data;
  